### ISSUE TITLE
R bindings for taxonkit?

### ISSUE THREAD

**Issue by johanneswerner** [shenwei356/taxonkit#41]
Hello, 

I am quite happy with `taxonkit` and discovered yesterday that there are is also `pytaxonkit` - is there also an R package with R bindings to `taxonkit`? 

If not, can anyone help me to start developing it? (I have developed R packages in the past, I am just not sure in how to connect the functionality of `taxonkit` inside R)

Thank you. 

PS: I know an issue is not the best location for this request, unfortunately I did not have a better idea.

**Comment by standage** [comment]
I wrote [Python bindings for TaxonKit](https://github.com/bioforensics/pytaxonkit) recently, if you’d like to use that as a reference. I primarily used the `Popen` construct in Python’s `subprocess` library to call TaxonKit, and then loaded the output into dataframes (pandas) for handling in Python.

https://github.com/bioforensics/pytaxonkit/blob/9746225b1c0a9eff708790037e3b53e5d45ac235/pytaxonkit.py#L203-L211

It’s been a long time since I did any serious work in R, so I’m not sure what the best tools are for system calls. But I imagine R’s native dataframes would be suitable for storing most results.

I hope this helps.

**Comment by johanneswerner** [comment]
Thank you very much. This is indeed helpful, I am just not quite sure on how to work with this information. :-) Thank you for the clarification in your package.

**Comment by shenwei356** [comment]
Sorry, I'm not familar with R package development :(

**Comment by johanneswerner** [comment]
For me, everything is cleared up. Thank you again.
